### ISSUE TITLE
RootNamespace emtpy not supported

### ISSUE THREAD

**Issue by narcis-ro** [VocaDB/ResXFileCodeGenerator#10]
Setting RootNamespace to empty generates the resource manager basename starting with a dot.
That’s mainly because of this:
https://github.com/VocaDB/ResXFileCodeGenerator/blob/d5696d9c0a61756beb716a3da10f684c09274b3f/VocaDb.ResXFileCodeGenerator/FileOptions.cs#L61

**Comment by ycanardeau** [comment]
Thanks, are you planning to make a pull request?

**Comment by narcis-ro** [comment]
@ycanardeau created PR for it here: https://github.com/VocaDB/ResXFileCodeGenerator/pull/11
