### ISSUE TITLE
IDE Intellisense not reflecting changes after resx file changes

### ISSUE THREAD

**Issue by narcis-ro** [VocaDB/ResXFileCodeGenerator#12]
**Steps to repro:**
- Add a new entry in a resx file 
- IDE should suggest the new key after "."

Workaround:
- Close/Open Visual Studio
- Rename the file twice

After understanding how incremental source generators work from the [docs](https://github.com/dotnet/roslyn/blob/main/docs/features/incremental-generators.md) it seems the issues has to do with caching and comparing.

As you know each stage in pipeline will be cached and compared, if it did not change, the source generator will use cached version, making it very fast. 

[Here](https://github.com/VocaDB/ResXFileCodeGenerator/blob/main/VocaDb.ResXFileCodeGenerator/SourceGenerator.cs#L15) the resx files are grouped, in a class [GroupedAdditionalFile ](https://github.com/VocaDB/ResXFileCodeGenerator/blob/main/VocaDb.ResXFileCodeGenerator/GroupedAdditionalFile.cs#L5) which implements `IEquatable`, and checks the paths for root resx file and sub-files. 
The problem with this is that the pipeline will consider the result as not changed if the paths didn't change, so it will **not** regenerate the source, although file content did change. So no new code generation, changes not visible in intellisense.

I'm working on a PR to clean things up a bit. Bellow is a summary of how things would work.

- Roslyn will trigger additional file changed when the file does actually change (tried it via direct editing in Visual Studio as well as File Explorer)
- Roslyn will trigger additional text file changed when first loading the solution (first time generating the file).

**When we should generate new source code:**
- When NOT using VocaDb Resx Manager
       - Any change of the root resx file  - culture specific files should not matter
       - global options change
       - file options/metadata change
       - file moved/deleted
- When using VocaDb Resx Manager
       - Any change of the root resx file or culture specific files
       - global options change
       - file options/metadata change
       - file moved/deleted

**When we should NOT generate new source code:**
       - building multiple times without any change to options, path or contents
       - changes to csproj that does not affect global or per file options

For the classic ResourceManager:
```
public void Initialize(IncrementalGeneratorInitializationContext context)
{
	var resxFiles = context.AdditionalTextsProvider.Where(static additionalText => additionalText.Path.EndsWith(".resx"));

		var rootResxFiles = resxFiles.Where(static resxFile => !s_matchCultureSpecificResxFiles.IsMatch(resxFile.Path));
		var rootResxFilesWithVersion = rootResxFiles.Select(static (rootResxFile, _) => new AdditionalTextWithHash(rootResxFile, Guid.NewGuid()));
		var analyzerOptions = context.AnalyzerConfigOptionsProvider;
	
		var fileWithOptions = rootResxFilesWithVersion
			.Combine(analyzerOptions)
			.Select(static (tuple, _) => new FileOptionsWithHash(new FileOptions(tuple.Left.File, tuple.Right.GetOptions(tuple.Left.File), new GlobalOptions(tuple.Right.GlobalOptions)), tuple.Left.Hash))
			.Where(static fileOptionsWithHash => fileOptionsWithHash.FileOptions.IsValid);
		
		context.RegisterSourceOutput(fileWithOptions, static (ctx, fileOptionsWithHash) =>
		{ 
			var (generatedFileName, sourceCode, errorsAndWarnings) = new StringBuilderGenerator().Generate(fileOptionsWithHash.FileOptions, ctx.CancellationToken);

			foreach (var errorOrWarning in errorsAndWarnings)
				ctx.ReportDiagnostic(errorOrWarning);

			ctx.AddSource(generatedFileName, sourceCode);
		});

     // TODO: Update VocaDb Resx Manager
}

private record AdditionalTextWithHash(AdditionalText File, Guid Hash); 

private record FileOptionsWithHash(FileOptions FileOptions, Guid Hash)
	{
		public virtual bool Equals(FileOptionsWithHash? other)
		{
			if (ReferenceEquals(null, other))
			{
				return false;
			}

			if (ReferenceEquals(this, other))
			{
				return true;
			}

			var sameOptions = FileOptions.FileOptionsWithoutContentComparer.Equals(FileOptions, other.FileOptions);
			var sameHash = Hash.Equals(other.Hash);

			return sameOptions && sameHash;
		}

		public override int GetHashCode()
		{
			unchecked
			{
				return (FileOptions.GetHashCode() * 397) ^ Hash.GetHashCode();
			}
		}
	}

```
`FileOptionsWithoutContentComparer` compares FileOptions without looking at the additional text file. Compare only merged Global + File Options, if these changed then source code needs to be refreshed.
Note: `AdditionalText` does not have any Equality comparer defined. So it will compare object references witch might change.

In order to have a simple pipeline, composable and cache-able I've used a helper random Guid (value type) inside a tuple which implements by default equality.

When context.AdditionalTextsProvider emits new value, it will be filtered to see if we are intersted in the changes (`rootResxFiles` files only). Then we will assigned it a Guid.NewGuid() which will act as version/hash of the file (we do not want to actually check file content, because roslyn already does that). 
We combine the `rootResxFilesWithVersion` with analyzerOptions in order to get global options as well as file options. Due to the combine, `rootResxFilesWithVersion` or `analyzerOptions` might emit new values independently. For example, other AdditionalTexts might change which might not be of interest to us, as well as other global/file analyzer options might change but irrelevant to resx source code generation. So in this stage we will emit a tuple which can be easily compared by the pipeline for equality.

`FileOptionsWithHash fileWithOptions` which consists of `FileOptions` class (Global + File analyzer options merged), and the original AdditionalText file hash. `RegisterSourceOutput` will be called only if the file contents or options have changed.

**What doesn't work for now**
   - Maybe this is a Roslyn bug, but whenever I change the embedded resx metadata, setting per file option e.g StaticClass=False, it seems that the `AdditionalTextsProvider` does not emit changes. It only works for Global options (be it in csproj or .editorconfig)

**Comment by ycanardeau** [comment]
Fixed in #13.
