### ISSUE TITLE
Generate internal class

### ISSUE THREAD

**Issue by mkaring** [VocaDB/ResXFileCodeGenerator#2]
Hello,
do you have any plans on adding the possibility to select if the generated code should have public or internal visibility? Most of my use-cases do not require public visible access to the resources and so I would really like to be able to change the visibility to avoid cluttering the public API.

Either a global property or a metadata entry for each file would be most suited to handle this I think.

**Comment by ycanardeau** [comment]
I've added an option `ResXFileCodeGenerator_PublicClass` to select if the generated code should have public or internal visibility. I haven't pushed the changes yet, but I'll publish a NuGet package tomorrow if possible.

**Comment by ycanardeau** [comment]
Now VocaDb.ResXFileCodeGenerator generates internal classes by default. You can change this behavior by setting 
`PublicClass` (per file) or `ResXFileCodeGenerator_PublicClass` (globally) to `true`. For more information, see [README.md](https://github.com/VocaDB/ResXFileCodeGenerator/blob/030f959ddff9cb9b9fed6dbcab64f65fa7c27338/README.md).

**Comment by mkaring** [comment]
That works perfectly. Thank you for the support.
