### ISSUE TITLE
Visual Studio 2022 - Culture not found for resource (resx file version 4.0.30319.42000)

### ISSUE THREAD

**Issue by danielanywhere** [VocaDB/ResXFileCodeGenerator#8]
### Problem
When managing MyResource.resx ... embedded file sets that rely upon ResXFileCodeGenerator in Visual Studio 2022, errors may be encountered similar to the following at runtime.

<blockquote>Exception thrown: 'System.Resources.MissingManifestResourceException' in System.Private.CoreLib.dll<br /><br />

Additional information: Could not find the resource "MyResource.resources" among the resources "MyControl.MyControl.resources", "MyControl.MyResource.resources" embedded in the assembly "MyControl", nor among the resources in any satellite assemblies for the specified culture. Perhaps the resources were embedded with an incorrect name.</blockquote>

During design time however, the elements will seem to be accessible due to the static local nature of the entries in the associated designer file (MyResource.Designer.cs).

### Context
This issue seems to occur mostly in conditions where the same resource file name is used in different projects on multi-project solutions.

For example, in cases where MainProject, ComponentProject1, and ComponentProject2 projects all have their own MyResource.resx files, each with different contents, a higher potential exists for encountering this issue.

### Cause
This issue is caused by an ambiguity during the initialization of ResourceManager in the automatically generated MyResource.Designer.cs file. The generated method is similar to the following.

<blockquote>/// &lt;summary&gt;<br />
///   Returns the cached ResourceManager instance used by this class.<br />
/// &lt;/summary&gt;<br />
[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]<br />
internal static global::System.Resources.ResourceManager ResourceManager {<br />
&nbsp;get {<br />
&nbsp;&nbsp;if (object.ReferenceEquals(resourceMan, null)) {<br />
&nbsp;&nbsp;&nbsp;global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("<b>MyResource</b>", typeof(<b>MyResource</b>).Assembly);<br />
&nbsp;&nbsp;&nbsp;resourceMan = temp;<br />
&nbsp;&nbsp;}<br />
&nbsp;&nbsp;return resourceMan;<br />
&nbsp;}<br />
}</blockquote>

The issue is centered in the above snippet on the specific content that becomes ambiguous at runtime:

`"MyResource", typeof(MyResource)`

### Workaround
To work around this issue, prefix each affected instance of MyResource with the namespace being serviced by that instance.

For example:

`"MyNamespace.MyResource", typeof(MyNamespace.MyResource)`

The following snippet demonstrates this change, as applied to the default snippet shown above.

<blockquote>/// &lt;summary&gt;<br />
///   Returns the cached ResourceManager instance used by this class.<br />
/// &lt;/summary&gt;<br />
[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]<br />
internal static global::System.Resources.ResourceManager ResourceManager {<br />
&nbsp;get {<br />
&nbsp;&nbsp;if (object.ReferenceEquals(resourceMan, null)) {<br />
&nbsp;&nbsp;&nbsp;global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("<b>MyNamespace.MyResource</b>", typeof(<b>MyNamespace.MyResource</b>).Assembly);<br />
&nbsp;&nbsp;&nbsp;resourceMan = temp;<br />
&nbsp;&nbsp;}<br />
&nbsp;&nbsp;return resourceMan;<br />
&nbsp;}<br />
}</blockquote>

**Comment by ycanardeau** [comment]
> For example, in cases where MainProject, ComponentProject1, and ComponentProject2 projects all have their own MyResource.resx files, each with different contents, a higher potential exists for encountering this issue.

Can you please provide a reproduction repository if possible?

**Comment by danielanywhere** [comment]
@ycanardeau, thank you for looking at this issue. I have created a small GitHub project that might help you with diagnosing this issue. You can find it at [https://github.com/danielanywhere/ResXFileCodeGeneratorIssues8Code](https://github.com/danielanywhere/ResXFileCodeGeneratorIssues8Code).

The project README contains information about reproducing. Please let me know if you need anything else.

**Comment by ycanardeau** [comment]
@danielanywhere Thank you for creating a small GitHub project, but I think you're confusing VocaDb.ResXFileCodeGenerator, a source generator, with the Microsoft's official ResXFileCodeGenerator, which are two different things.

**Comment by danielanywhere** [comment]
@ycanardeau, I apologize for misunderstanding. Will continue to look for the MS ResXFileCodeGenerator then. Thank you for the interaction, and good luck on this specific project.
