### ISSUE TITLE
Question and Possible Bug

### ISSUE THREAD

**Issue by TorreyGarland** [VocaDB/ResXFileCodeGenerator#9]
How is this different or better than the built-in resource designer/generators?

Possible Bug: Not working in a .NET 6 class library or console app.

**Comment by ycanardeau** [comment]
> How is this different or better than the built-in resource designer/generators?

The original motivation of this source generator was to leave auto-generated code (*.Designer.cs) outside source control (See https://github.com/VocaDB/vocadb/commit/e90b9499ba37787552634787312c79b3ea9837bb).

> Possible Bug: Not working in a .NET 6 class library or console app.

It should work in a .NET 6 class library (See [VocaDB/vocadb-loc](https://github.com/VocaDB/vocadb-loc)). Can you please provide a reproduction repository?

**Comment by Malysh-ok** [comment]
Hay!
1) Tell me how to set up auto-generation when saving resources in the Localization Manager?
2) How to start generation? It only works for me when installing the nuget package.
3) How do I set the folder where the resulting cs file will be created?

**Comment by Malysh-ok** [comment]
I change resources, I test - I get an error.
I reboot the nuget package - everything works.

UPD. Although no, it doesn't work. (

![изображение](https://user-images.githubusercontent.com/111501366/185397388-a9604f25-0b0d-4c27-9d56-cda2910d1bf9.png)

**Comment by Malysh-ok** [comment]
> > How is this different or better than the built-in resource designer/generators?
> 
> The original motivation of this source generator was to leave auto-generated code (*.Designer.cs) outside source control (See [VocaDB/vocadb@e90b949](https://github.com/VocaDB/vocadb/commit/e90b9499ba37787552634787312c79b3ea9837bb)).
> 
> > Possible Bug: Not working in a .NET 6 class library or console app.
> 
> It should work in a .NET 6 class library (See [VocaDB/vocadb-loc](https://github.com/VocaDB/vocadb-loc)). Can you please provide a reproduction repository?

Greetings.
Could you answer my questions above?

**Comment by Malysh-ok** [comment]
Dear developers!
Give answers to my questions, please.

**Comment by ycanardeau** [comment]
Please provide a reproduction repository.
